# Generated by Django 3.1.3 on 2020-11-28 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargosEmpleado',
            fields=[
                ('nom_cargo', models.CharField(db_column='Nom_cargo', max_length=50, primary_key=True, serialize=False)),
                ('salario', models.IntegerField(db_column='Salario')),
                ('horas_semanales', models.SmallIntegerField(db_column='Horas_semanales')),
            ],
            options={
                'db_table': 'Cargos_empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarritosCompra',
            fields=[
                ('id_carrito', models.SmallAutoField(db_column='Id_carrito', primary_key=True, serialize=False)),
                ('num_item', models.SmallIntegerField(db_column='Num_item')),
                ('fecha_ingreso', models.DateField(blank=True, db_column='Fecha_ingreso', null=True)),
                ('fecha_caducidad', models.DateField(db_column='Fecha_caducidad')),
                ('checkout', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Carritos_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.SmallIntegerField(db_column='Id_categoria', primary_key=True, serialize=False)),
                ('tipo_inmueble', models.CharField(db_column='Tipo_inmueble', max_length=50)),
            ],
            options={
                'db_table': 'Categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cedula_ciudadania', models.BigIntegerField(db_column='Cedula_ciudadania', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('apellido', models.CharField(db_column='Apellido', max_length=50)),
                ('direccion', models.CharField(db_column='Direccion', max_length=50)),
                ('ciudad', models.CharField(db_column='Ciudad', max_length=50)),
                ('numero_telefono', models.BigIntegerField(db_column='Numero_telefono')),
            ],
            options={
                'db_table': 'Clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.SmallAutoField(db_column='Id_empleado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('apellido', models.CharField(db_column='Apellido', max_length=50)),
                ('cedula_empleado', models.BigIntegerField(db_column='Cedula_empleado')),
            ],
            options={
                'db_table': 'Empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id_extra', models.SmallIntegerField(db_column='Id_extra', primary_key=True, serialize=False)),
                ('nombre_extra', models.CharField(db_column='Nombre_extra', max_length=45)),
                ('cantidad', models.SmallIntegerField(db_column='Cantidad')),
            ],
            options={
                'db_table': 'Extras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inmuebles',
            fields=[
                ('id_inmueble', models.SmallIntegerField(db_column='Id_inmueble', primary_key=True, serialize=False)),
                ('direccion_inmueble', models.CharField(db_column='Direccion_inmueble', max_length=50)),
                ('sector', models.CharField(db_column='Sector', max_length=50)),
                ('area', models.DecimalField(db_column='Area', decimal_places=3, max_digits=8)),
                ('numero_habitaciones', models.SmallIntegerField(blank=True, db_column='Numero_habitaciones', null=True)),
                ('numero_baños', models.SmallIntegerField(blank=True, db_column='Numero_baños', null=True)),
                ('estrato', models.SmallIntegerField(db_column='Estrato')),
                ('precio', models.BigIntegerField(db_column='Precio')),
                ('antiguedad', models.IntegerField(db_column='Antiguedad')),
            ],
            options={
                'db_table': 'Inmuebles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('num_venta', models.SmallAutoField(db_column='Num_venta', primary_key=True, serialize=False)),
                ('pago_inicial', models.BigIntegerField(db_column='Pago_inicial')),
                ('pago_final', models.BigIntegerField(db_column='Pago_final')),
                ('fecha', models.DateField(db_column='Fecha')),
            ],
            options={
                'db_table': 'Ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManyInmuebleHasManyCarritoCompra',
            fields=[
                ('id_inmueble_inmueble', models.OneToOneField(db_column='Id_inmueble_Inmueble', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tienda_virtual.inmuebles')),
            ],
            options={
                'db_table': 'many_Inmueble_has_many_Carrito_compra',
                'managed': False,
            },
        ),
    ]
