# Generated by Django 3.1.3 on 2020-12-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_virtual', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManyInmuebleHasManyCarritoCompra',
        ),
    ]
