# Generated by Django 3.1.3 on 2020-11-09 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CargosEmpleado',
            fields=[
                ('nom_cargo', models.CharField(db_column='Nom_cargo', max_length=50, primary_key=True, serialize=False)),
                ('salario', models.IntegerField(db_column='Salario')),
                ('horas_semanales', models.SmallIntegerField(db_column='Horas_semanales')),
            ],
            options={
                'db_table': 'Cargos_empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarritosCompra',
            fields=[
                ('id_carrito', models.SmallAutoField(db_column='Id_carrito', primary_key=True, serialize=False)),
                ('num_item', models.SmallIntegerField(db_column='Num_item')),
                ('fecha_ingreso', models.DateField(blank=True, db_column='Fecha_ingreso', null=True)),
                ('fecha_caducidad', models.DateField(db_column='Fecha_caducidad')),
                ('checkout', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Carritos_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.SmallIntegerField(db_column='Id_categoria', primary_key=True, serialize=False)),
                ('tipo_inmueble', models.CharField(db_column='Tipo_inmueble', max_length=50)),
            ],
            options={
                'db_table': 'Categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cedula_ciudadania', models.BigIntegerField(db_column='Cedula_ciudadania', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('apellido', models.CharField(db_column='Apellido', max_length=50)),
                ('direccion', models.CharField(db_column='Direccion', max_length=50)),
                ('ciudad', models.CharField(db_column='Ciudad', max_length=50)),
                ('numero_telefono', models.BigIntegerField(db_column='Numero_telefono')),
            ],
            options={
                'db_table': 'Clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.SmallAutoField(db_column='Id_empleado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('apellido', models.CharField(db_column='Apellido', max_length=50)),
                ('cedula_empleado', models.BigIntegerField(db_column='Cedula_empleado')),
            ],
            options={
                'db_table': 'Empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id_extra', models.SmallIntegerField(db_column='Id_extra', primary_key=True, serialize=False)),
                ('nombre_extra', models.SmallIntegerField(db_column='Nombre_extra')),
                ('cantidad', models.SmallIntegerField(blank=True, db_column='Cantidad', null=True)),
            ],
            options={
                'db_table': 'Extras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inmuebles',
            fields=[
                ('id_inmueble', models.SmallIntegerField(db_column='Id_inmueble', primary_key=True, serialize=False)),
                ('direccion_inmueble', models.CharField(db_column='Direccion_inmueble', max_length=50)),
                ('sector', models.CharField(db_column='Sector', max_length=50)),
                ('area', models.DecimalField(db_column='Area', decimal_places=3, max_digits=8)),
                ('numero_habitaciones', models.SmallIntegerField(blank=True, db_column='Numero_habitaciones', null=True)),
                ('numero_baños', models.SmallIntegerField(blank=True, db_column='Numero_baños', null=True)),
                ('estrato', models.SmallIntegerField(db_column='Estrato')),
                ('precio', models.BigIntegerField(db_column='Precio')),
                ('antiguedad', models.IntegerField(db_column='Antiguedad')),
            ],
            options={
                'db_table': 'Inmuebles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('num_venta', models.SmallAutoField(db_column='Num_venta', primary_key=True, serialize=False)),
                ('pago_inicial', models.BigIntegerField(db_column='Pago_inicial')),
                ('pago_final', models.BigIntegerField(db_column='Pago_final')),
                ('fecha', models.DateField(db_column='Fecha')),
                ('id_empleado', models.SmallIntegerField(blank=True, db_column='Id_empleado', null=True)),
            ],
            options={
                'db_table': 'Ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManyInmuebleHasManyCarritoCompra',
            fields=[
                ('id_inmueble_inmueble', models.OneToOneField(db_column='Id_inmueble_Inmueble', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='register.inmuebles')),
            ],
            options={
                'db_table': 'many_Inmueble_has_many_Carrito_compra',
                'managed': False,
            },
        ),
    ]
